from . import admission
from . import departmentBilling
from . import discharge
from . import doctormaster
from . import grn
from . import ICD11
from . import inventory
from . import pharmacy
from . import radiology
from . import room
from . import stock
from . import summary
from . import dashboard
