# Generated by Django 3.2 on 2026-02-04 04:37

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Billing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('lastmodified_by', models.CharField(blank=True, max_length=100, null=True)),
                ('lastmodified_date', models.DateTimeField(auto_now=True)),
                ('registration_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('consulting_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_fees', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('payment_method', models.CharField(blank=True, max_length=50, null=True)),
                ('bill_number', models.CharField(blank=True, max_length=50, unique=True)),
                ('billed_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IPGRN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('lastmodified_by', models.CharField(blank=True, max_length=100, null=True)),
                ('lastmodified_date', models.DateTimeField(auto_now=True)),
                ('grn_number', models.CharField(max_length=50, unique=True)),
                ('vendor_id', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('invoice_no', models.CharField(max_length=50)),
                ('invoice_date', models.DateField()),
                ('credit_period', models.CharField(blank=True, max_length=100, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('payment_mode', models.CharField(blank=True, max_length=50, null=True)),
                ('purchase_category', models.CharField(default='IP PHARMACY', max_length=50)),
                ('taxable_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('non_taxable_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('tax_paid_to_supplier', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('cgst', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('sgst', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('igst', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('cess', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('central_sales_tax', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('local_tax', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('round_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('net_invoice_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('total_discount', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('tax_on_free_items', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('quotation_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('courier_transport_charge', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('items', models.TextField()),
                ('payment_status', models.TextField(blank=True, null=True)),
                ('total_amount_paid', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('remarks', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IPPharmacyStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('lastmodified_by', models.CharField(blank=True, max_length=100, null=True)),
                ('lastmodified_date', models.DateTimeField(auto_now=True)),
                ('ip_stock_id', models.CharField(max_length=10, unique=True)),
                ('medicine_name', models.CharField(max_length=255)),
                ('batch_number', models.CharField(max_length=100)),
                ('hsn_code', models.CharField(blank=True, max_length=100, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('purchase_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('purchase_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('mrp', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('taxable_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('cgst_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('cgst_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('sgst_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('sgst_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('total_quantity', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OPGRN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('lastmodified_by', models.CharField(blank=True, max_length=100, null=True)),
                ('lastmodified_date', models.DateTimeField(auto_now=True)),
                ('grn_number', models.CharField(max_length=50, unique=True)),
                ('vendor_id', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('invoice_no', models.CharField(max_length=50)),
                ('invoice_date', models.DateField()),
                ('credit_period', models.CharField(blank=True, max_length=100, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('payment_mode', models.CharField(blank=True, max_length=50, null=True)),
                ('purchase_category', models.CharField(default='OP PHARMACY', max_length=50)),
                ('taxable_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('non_taxable_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('tax_paid_to_supplier', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('cgst', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('sgst', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('igst', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('cess', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('central_sales_tax', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('local_tax', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('round_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('net_invoice_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('total_discount', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('tax_on_free_items', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('quotation_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('courier_transport_charge', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('items', models.TextField()),
                ('payment_status', models.TextField(blank=True, null=True)),
                ('total_amount_paid', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('remarks', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OPPharmacyStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('lastmodified_by', models.CharField(blank=True, max_length=100, null=True)),
                ('lastmodified_date', models.DateTimeField(auto_now=True)),
                ('op_stock_id', models.CharField(max_length=10, unique=True)),
                ('medicine_name', models.CharField(max_length=255)),
                ('batch_number', models.CharField(max_length=100)),
                ('hsn_code', models.CharField(blank=True, max_length=100, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('purchase_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('purchase_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('mrp', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('taxable_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('cgst_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('cgst_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('sgst_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('sgst_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('total_quantity', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.DeleteModel(
            name='PharmacyStock',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='doctor_name',
            new_name='doctorName',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='mobile_phone',
            new_name='mobilePhone',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='referred_by',
            new_name='referredBy',
        ),
        migrations.RemoveField(
            model_name='admission',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='block',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='ctreport',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='dischargedetail',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='estimatebilling',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='investbilling',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='log',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='mrireport',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='consulting_fee',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='registration_fee',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='salutation',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='total_fees',
        ),
        migrations.RemoveField(
            model_name='referencedoctor',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='room',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='roomcategory',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='service',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='summary',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='usgreport',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='xrayreport',
            name='is_active',
        ),
        migrations.AddField(
            model_name='vendor',
            name='account_on_hold',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vendor',
            name='blacklisted_supplier',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vendor',
            name='credit_period',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='export_data_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='gstin',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='igst_supplier',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vendor',
            name='kgst_tin_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='payment',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='reason_for_holding',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='tds_percent',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='terms',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='address_line_1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='pincode',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='url',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='vendor_id',
            field=models.CharField(max_length=10, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AddField(
            model_name='billing',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billings', to='hospital.patient'),
        ),
    ]
