# Generated by Django 3.2 on 2026-03-16 06:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_auto_20260204_1007'),
    ]

    operations = [
        migrations.CreateModel(
            name='GRN',
            fields=[
                ('hospital_code', models.CharField(blank=True, default='SH001', max_length=100, null=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('created_date', models.DateTimeField(blank=True, null=True)),
                ('lastmodified_by', models.CharField(blank=True, max_length=100, null=True)),
                ('lastmodified_date', models.DateTimeField(blank=True, null=True)),
                ('draft_number', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('grn_number', models.CharField(blank=True, max_length=50, unique=True)),
                ('date', models.DateTimeField()),
                ('purchase_category', models.CharField(max_length=50)),
                ('vendor_id', models.IntegerField()),
                ('grn_type', models.CharField(default='INVOICE', max_length=20)),
                ('invoice_no', models.CharField(max_length=100)),
                ('invoice_date', models.DateTimeField()),
                ('payment_mode', models.CharField(max_length=20)),
                ('items', models.TextField(default='[]')),
                ('taxable_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('non_taxable_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('cgst', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('sgst', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('igst', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('tax_paid_to_supplier', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_discount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('round_amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('net_invoice_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('payment_status', models.TextField(default='[]')),
                ('remarks', models.TextField(blank=True, default='')),
                ('status', models.CharField(default='Draft', max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OPPharmacyBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospital_code', models.CharField(blank=True, default='SH001', max_length=100, null=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('created_date', models.DateTimeField(blank=True, null=True)),
                ('lastmodified_by', models.CharField(blank=True, max_length=100, null=True)),
                ('lastmodified_date', models.DateTimeField(blank=True, null=True)),
                ('bill_no', models.CharField(max_length=50)),
                ('bill_date', models.CharField(max_length=20)),
                ('op_number', models.CharField(max_length=50)),
                ('inpatient_number', models.CharField(blank=True, max_length=50, null=True)),
                ('patient_name', models.CharField(max_length=100)),
                ('doctor', models.CharField(max_length=100)),
                ('room_no', models.CharField(blank=True, max_length=20, null=True)),
                ('medicine_name', models.JSONField()),
                ('net_amount', models.FloatField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PharmacyCategory',
            fields=[
                ('hospital_code', models.CharField(blank=True, default='SH001', max_length=100, null=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('created_date', models.DateTimeField(blank=True, null=True)),
                ('lastmodified_by', models.CharField(blank=True, max_length=100, null=True)),
                ('lastmodified_date', models.DateTimeField(blank=True, null=True)),
                ('category_id', models.IntegerField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PharmacyItem',
            fields=[
                ('hospital_code', models.CharField(blank=True, default='SH001', max_length=100, null=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('created_date', models.DateTimeField(blank=True, null=True)),
                ('lastmodified_by', models.CharField(blank=True, max_length=100, null=True)),
                ('lastmodified_date', models.DateTimeField(blank=True, null=True)),
                ('item_id', models.IntegerField(primary_key=True, serialize=False)),
                ('item_name', models.CharField(max_length=200)),
                ('item_last_name', models.CharField(blank=True, max_length=200)),
                ('category', models.CharField(max_length=50)),
                ('hsn', models.CharField(blank=True, max_length=50)),
                ('high_risk', models.BooleanField(default=False)),
                ('look_alike', models.BooleanField(default=False)),
                ('sound_alike', models.BooleanField(default=False)),
                ('reorder_level', models.IntegerField(default=0)),
                ('IP_shelf_no', models.CharField(blank=True, max_length=50)),
                ('IP_rack_no', models.CharField(blank=True, max_length=50)),
                ('OP_shelf_no', models.CharField(blank=True, max_length=50)),
                ('OP_rack_no', models.CharField(blank=True, max_length=50)),
                ('G_shelf_no', models.CharField(blank=True, max_length=50)),
                ('G_rack_no', models.CharField(blank=True, max_length=50)),
                ('IP_available', models.BooleanField(default=False)),
                ('OP_available', models.BooleanField(default=False)),
                ('G_available', models.BooleanField(default=False)),
                ('is_blocked', models.BooleanField(default=False)),
                ('blocked_reason', models.CharField(blank=True, max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PharmacyStock',
            fields=[
                ('hospital_code', models.CharField(blank=True, default='SH001', max_length=100, null=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('created_date', models.DateTimeField(blank=True, null=True)),
                ('lastmodified_by', models.CharField(blank=True, max_length=100, null=True)),
                ('lastmodified_date', models.DateTimeField(blank=True, null=True)),
                ('stock_id', models.IntegerField(primary_key=True, serialize=False)),
                ('department_code', models.CharField(max_length=20)),
                ('item_id', models.IntegerField()),
                ('batch_number', models.CharField(max_length=50)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('mrp', models.DecimalField(decimal_places=2, max_digits=10)),
                ('grn_number', models.CharField(max_length=50)),
                ('total_stock', models.IntegerField()),
                ('sold_quantity', models.IntegerField(default=0)),
                ('transferred_out_quantity', models.IntegerField(default=0)),
                ('stock_type', models.CharField(default='grn', max_length=50)),
                ('stock_ref_id', models.IntegerField(default=0)),
                ('grn_return_quantity', models.IntegerField(default=0)),
                ('grn_return_ref_id', models.IntegerField(blank=True, null=True)),
                ('blocked_quantity', models.IntegerField(default=0)),
                ('sales_return_quantity', models.IntegerField(default=0)),
                ('sales_return_ref_id', models.IntegerField(blank=True, null=True)),
                ('CGST_Percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('SGST_Percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('CGST_Amt', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('SGST_Amt', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='bed',
            name='room',
        ),
        migrations.DeleteModel(
            name='IPGRN',
        ),
        migrations.DeleteModel(
            name='IPPharmacyStock',
        ),
        migrations.DeleteModel(
            name='OPGRN',
        ),
        migrations.DeleteModel(
            name='OPPharmacyStock',
        ),
        migrations.DeleteModel(
            name='Service',
        ),
        migrations.AlterModelOptions(
            name='admission',
            options={'ordering': ['-admissionDateTime']},
        ),
        migrations.RenameField(
            model_name='roomcategory',
            old_name='ward_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='admission',
            name='admissionDate',
        ),
        migrations.RemoveField(
            model_name='admission',
            name='admissionFee',
        ),
        migrations.RemoveField(
            model_name='admission',
            name='age',
        ),
        migrations.RemoveField(
            model_name='admission',
            name='birthTime',
        ),
        migrations.RemoveField(
            model_name='admission',
            name='callRelease',
        ),
        migrations.RemoveField(
            model_name='admission',
            name='customerType',
        ),
        migrations.RemoveField(
            model_name='admission',
            name='extensionNumber',
        ),
        migrations.RemoveField(
            model_name='admission',
            name='firstName',
        ),
        migrations.RemoveField(
            model_name='admission',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='admission',
            name='lastName',
        ),
        migrations.RemoveField(
            model_name='admission',
            name='middleName',
        ),
        migrations.RemoveField(
            model_name='admission',
            name='mlcRemarks',
        ),
        migrations.RemoveField(
            model_name='admission',
            name='mlcType',
        ),
        migrations.RemoveField(
            model_name='admission',
            name='mothersUHIDNo',
        ),
        migrations.RemoveField(
            model_name='admission',
            name='nursingStation',
        ),
        migrations.RemoveField(
            model_name='admission',
            name='passAlertToAuthority',
        ),
        migrations.RemoveField(
            model_name='admission',
            name='pediatricianResponsible',
        ),
        migrations.RemoveField(
            model_name='admission',
            name='presentComplaints',
        ),
        migrations.RemoveField(
            model_name='admission',
            name='salutation',
        ),
        migrations.RemoveField(
            model_name='admission',
            name='time',
        ),
        migrations.RemoveField(
            model_name='admission',
            name='uploadMLCDoc',
        ),
        migrations.RemoveField(
            model_name='admission',
            name='weight',
        ),
        migrations.RemoveField(
            model_name='block',
            name='id',
        ),
        migrations.RemoveField(
            model_name='estimatebilling',
            name='middleName',
        ),
        migrations.RemoveField(
            model_name='room',
            name='id',
        ),
        migrations.RemoveField(
            model_name='roomcategory',
            name='description',
        ),
        migrations.RemoveField(
            model_name='roomcategory',
            name='id',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='account_on_hold',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='address_line_1',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='address_line_2',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='blacklisted_supplier',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='credit_period',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='export_data_code',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='igst_supplier',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='kgst_tin_number',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='payment',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='reason_for_holding',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='tds_percent',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='terms',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='url',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='vendor_type',
        ),
        migrations.AddField(
            model_name='admission',
            name='admissionDateTime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='admission',
            name='advance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='admission',
            name='advance_payments',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='admission',
            name='hospital_code',
            field=models.CharField(blank=True, default='SH001', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='admission',
            name='ip_advance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='admission',
            name='ipserial_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='admission',
            name='is_admissionActive',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='admission',
            name='is_advanceActive',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='admission',
            name='is_discharged',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='admission',
            name='is_roomActive',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='admission',
            name='is_roomCleaned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='admission',
            name='mlc_doc',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='admission',
            name='mlc_remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='admission',
            name='mlc_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='admission',
            name='packageName',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='admission',
            name='refunded_Amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='admission',
            name='roomShitingDetails',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='admission',
            name='total_advance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='billing',
            name='hospital_code',
            field=models.CharField(blank=True, default='SH001', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='block',
            name='hospital_code',
            field=models.CharField(blank=True, default='SH001', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='block',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='ctreport',
            name='hospital_code',
            field=models.CharField(blank=True, default='SH001', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='dischargedetail',
            name='hospital_code',
            field=models.CharField(blank=True, default='SH001', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='hospital_code',
            field=models.CharField(blank=True, default='SH001', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='estimatebilling',
            name='hospital_code',
            field=models.CharField(blank=True, default='SH001', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='estimatebilling',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='investbilling',
            name='hospital_code',
            field=models.CharField(blank=True, default='SH001', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='log',
            name='hospital_code',
            field=models.CharField(blank=True, default='SH001', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='mrireport',
            name='hospital_code',
            field=models.CharField(blank=True, default='SH001', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='hospital_code',
            field=models.CharField(blank=True, default='SH001', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='salutation',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='referencedoctor',
            name='hospital_code',
            field=models.CharField(blank=True, default='SH001', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='beds',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='room',
            name='blocked_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='room',
            name='enable_luxury_tax',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='room',
            name='hospital_code',
            field=models.CharField(blank=True, default='SH001', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='include_in_final_bill',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='room',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='room',
            name='occupancy',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='room',
            name='room_blocked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='room',
            name='room_kits',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='room',
            name='room_status',
            field=models.CharField(default='Available', max_length=20),
        ),
        migrations.AddField(
            model_name='room',
            name='services',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='roomcategory',
            name='hospital_code',
            field=models.CharField(blank=True, default='SH001', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='roomcategory',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='roomcategory',
            name='room_category_id',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='summary',
            name='hospital_code',
            field=models.CharField(blank=True, default='SH001', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='summary',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='usgreport',
            name='hospital_code',
            field=models.CharField(blank=True, default='SH001', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='address_line1',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vendor',
            name='address_line2',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='vendor',
            name='hospital_code',
            field=models.CharField(blank=True, default='SH001', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='payment_terms',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='vendor',
            name='supplier_type',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='xrayreport',
            name='hospital_code',
            field=models.CharField(blank=True, default='SH001', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='admission',
            name='consultingDoctor',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='admission',
            name='created_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='admission',
            name='creditLimit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='admission',
            name='ipNumber',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='admission',
            name='lastmodified_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='admission',
            name='reasonForAdmission',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='billing',
            name='created_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='billing',
            name='lastmodified_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='block',
            name='block_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='block',
            name='created_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='block',
            name='lastmodified_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ctreport',
            name='created_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ctreport',
            name='lastmodified_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dischargedetail',
            name='created_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dischargedetail',
            name='lastmodified_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='created_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='lastmodified_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='estimatebilling',
            name='created_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='estimatebilling',
            name='lastName',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='estimatebilling',
            name='lastmodified_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='investbilling',
            name='created_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='investbilling',
            name='lastmodified_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='log',
            name='created_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='log',
            name='lastmodified_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mrireport',
            name='created_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mrireport',
            name='lastmodified_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='created_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='lastmodified_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='referencedoctor',
            name='created_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='referencedoctor',
            name='lastmodified_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='created_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='lastmodified_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='nursing_station',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_number',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_type',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='roomcategory',
            name='created_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='roomcategory',
            name='lastmodified_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='summary',
            name='created_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='summary',
            name='lastmodified_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usgreport',
            name='created_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usgreport',
            name='lastmodified_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='city',
            field=models.CharField(blank=True, default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vendor',
            name='contact_person',
            field=models.CharField(blank=True, default=1, max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vendor',
            name='created_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='email',
            field=models.EmailField(blank=True, default=1, max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vendor',
            name='gstin',
            field=models.CharField(blank=True, default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vendor',
            name='lastmodified_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='phone',
            field=models.CharField(blank=True, default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vendor',
            name='pincode',
            field=models.CharField(blank=True, default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vendor',
            name='state',
            field=models.CharField(blank=True, default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vendor',
            name='vendor_id',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='xrayreport',
            name='created_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='xrayreport',
            name='lastmodified_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Bed',
        ),
    ]
