# Generated by Django 3.2 on 2026-02-06 07:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_auto_20260204_1007'),
    ]

    operations = [
        migrations.CreateModel(
            name='HSNCode',
            fields=[
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('lastmodified_by', models.CharField(blank=True, max_length=100, null=True)),
                ('lastmodified_date', models.DateTimeField(auto_now=True)),
                ('chapter', models.CharField(max_length=50)),
                ('hsn_code', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('description', models.TextField()),
                ('tax', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OPPharmacyBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('lastmodified_by', models.CharField(blank=True, max_length=100, null=True)),
                ('lastmodified_date', models.DateTimeField(auto_now=True)),
                ('bill_no', models.CharField(max_length=50)),
                ('bill_date', models.CharField(max_length=20)),
                ('op_number', models.CharField(max_length=50)),
                ('inpatient_number', models.CharField(blank=True, max_length=50, null=True)),
                ('patient_name', models.CharField(max_length=100)),
                ('doctor', models.CharField(max_length=100)),
                ('room_no', models.CharField(blank=True, max_length=20, null=True)),
                ('medicine_name', models.JSONField()),
                ('net_amount', models.FloatField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PharmacyStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('lastmodified_by', models.CharField(blank=True, max_length=100, null=True)),
                ('lastmodified_date', models.DateTimeField(auto_now=True)),
                ('invoice_number', models.CharField(max_length=100)),
                ('invoice_date', models.DateField()),
                ('supplier_name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=15)),
                ('gst_number', models.CharField(max_length=15)),
                ('address', models.CharField(max_length=15)),
                ('medicine_name', models.CharField(max_length=255)),
                ('batch_number', models.CharField(max_length=100)),
                ('hsn_code', models.CharField(max_length=100)),
                ('expiry_date', models.DateField()),
                ('quantity', models.IntegerField()),
                ('pack', models.IntegerField()),
                ('free', models.IntegerField(default=0)),
                ('purchase_rate', models.DecimalField(decimal_places=5, max_digits=10)),
                ('purchase_cost', models.DecimalField(decimal_places=5, max_digits=10)),
                ('mrp', models.DecimalField(decimal_places=5, max_digits=10)),
                ('discount', models.DecimalField(decimal_places=5, max_digits=10)),
                ('taxable_amount', models.DecimalField(decimal_places=5, max_digits=10)),
                ('cgst_rate', models.DecimalField(decimal_places=5, max_digits=10)),
                ('cgst_amount', models.DecimalField(decimal_places=5, max_digits=10)),
                ('sgst_rate', models.DecimalField(decimal_places=5, max_digits=10)),
                ('sgst_amount', models.DecimalField(decimal_places=5, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=5, max_digits=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Ventor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('lastmodified_by', models.CharField(blank=True, max_length=100, null=True)),
                ('lastmodified_date', models.DateTimeField(auto_now=True)),
                ('ventor_name', models.CharField(max_length=100, unique=True)),
                ('supplier_type', models.CharField(choices=[('Supplier', 'Supplier'), ('Manufacturer', 'Manufacturer'), ('Both', 'Both')], default='Supplier', max_length=20)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('landline', models.CharField(blank=True, max_length=15, null=True)),
                ('address', models.TextField()),
                ('gst_number', models.CharField(max_length=15, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='billing',
            name='doctor_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='salutation',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
