# Generated by Django 3.2 on 2026-02-11 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0003_auto_20260206_1328'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='approved_amount',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='citizen_id_no',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='citizen_id_type',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='customer_type',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='insurance_company',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='kin_address',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='kin_age',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='kin_age_unit',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='kin_mobile',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='kin_occupation',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='member_number',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='next_of_kin',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='referred_dr_mobile',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='referred_dr_remarks',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='relation',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='suffix_number',
        ),
        migrations.AddField(
            model_name='estimatebilling',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='summary',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
