# Generated by Django 3.2 on 2026-03-19 10:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0003_auto_20260316_1209'),
    ]

    operations = [
        migrations.CreateModel(
            name='DischargeBilling',
            fields=[
                ('hospital_code', models.CharField(blank=True, default='SH001', max_length=100, null=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('created_date', models.DateTimeField(blank=True, null=True)),
                ('lastmodified_by', models.CharField(blank=True, max_length=100, null=True)),
                ('lastmodified_date', models.DateTimeField(blank=True, null=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(db_index=True, max_length=20)),
                ('estimate_number', models.CharField(blank=True, max_length=60, null=True, unique=True)),
                ('bill_no', models.CharField(blank=True, max_length=60, null=True, unique=True)),
                ('uhid', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('ip_number', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('bill_date', models.DateField(default=django.utils.timezone.now)),
                ('items', models.JSONField(default=list)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('advance_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('sales_return', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('medicines_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('taxable_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('non_tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('gst_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('room_tax', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('discount_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('disc_reason', models.CharField(blank=True, max_length=300, null=True)),
                ('item_disc', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_disc', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('net_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('converted_from_id', models.IntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='insurance_company',
            new_name='company_code',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='kin_mobile',
            new_name='emergency_contact',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='referred_dr_mobile',
            new_name='referred_doctor_phone',
        ),
        migrations.RemoveField(
            model_name='admission',
            name='advance',
        ),
        migrations.RemoveField(
            model_name='admission',
            name='bedNo',
        ),
        migrations.RemoveField(
            model_name='admission',
            name='creditLimit',
        ),
        migrations.RemoveField(
            model_name='admission',
            name='ip_advance',
        ),
        migrations.RemoveField(
            model_name='admission',
            name='is_roomActive',
        ),
        migrations.RemoveField(
            model_name='admission',
            name='is_roomCleaned',
        ),
        migrations.RemoveField(
            model_name='admission',
            name='refunded_Amount',
        ),
        migrations.RemoveField(
            model_name='admission',
            name='roomNo',
        ),
        migrations.RemoveField(
            model_name='admission',
            name='total_advance',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='approved_amount',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='citizen_id_no',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='citizen_id_type',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='kin_address',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='kin_age',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='kin_age_unit',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='kin_occupation',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='member_number',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='next_of_kin',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='referred_dr_remarks',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='relation',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='suffix_number',
        ),
        migrations.AddField(
            model_name='admission',
            name='room_details',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='admission',
            name='roomShitingDetails',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='customer_type',
            field=models.CharField(choices=[('General', 'General'), ('Insurance', 'Insurance'), ('Corporate', 'Corporate'), ('Employee', 'Employee'), ('Staff', 'Staff'), ('Family', 'Family')], default='General', max_length=20),
        ),
    ]
