# Generated by Django 3.2 on 2026-02-11 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0003_auto_20260206_1328'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='emergency_contact',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='referred_doctor_phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
