# Generated by Django 3.2 on 2026-02-11 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0005_auto_20260211_1610'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='customer_type',
            field=models.CharField(choices=[('New', 'New'), ('Renew', 'Renew'), ('Visit', 'Visit')], default='New', max_length=20),
        ),
    ]
