# Generated by Django 3.2 on 2026-02-11 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0006_patient_customer_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='customer_type',
            field=models.CharField(choices=[('General', 'General'), ('Insurance', 'Insurance'), ('Corporate', 'Corporate')], default='General', max_length=20),
        ),
    ]
