# Generated by Django 3.2 on 2026-02-11 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0007_alter_patient_customer_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='billing',
            name='payment_status',
            field=models.CharField(choices=[('Paid', 'Paid'), ('Pending', 'Pending'), ('Unpaid', 'Unpaid')], default='Pending', max_length=20),
        ),
    ]
