# Generated by Django 3.2 on 2026-02-11 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0008_billing_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='billing',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
