# Generated by Django 3.2 on 2026-02-16 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0009_billing_transaction_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='TempPatientRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=100, unique=True)),
                ('data', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_consumed', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='billing',
            name='id',
        ),
        migrations.AddField(
            model_name='billing',
            name='paid_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='billing',
            name='bill_number',
            field=models.CharField(blank=True, max_length=50, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='customer_type',
            field=models.CharField(choices=[('General', 'General'), ('Insurance', 'Insurance'), ('Corporate', 'Corporate'), ('Employee', 'Employee'), ('Staff', 'Staff'), ('Family', 'Family')], default='General', max_length=20),
        ),
    ]
