# Generated by Django 3.2 on 2026-02-23 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0011_insuranceprovider'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='insuranceprovider',
            name='id',
        ),
        migrations.AddField(
            model_name='patient',
            name='company_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='insuranceprovider',
            name='company_code',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
