# Generated by Django 3.2 on 2026-04-03 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0004_auto_20260319_1628'),
        ('hospital', '0012_auto_20260223_1042'),
    ]

    operations = [
    ]
