# Generated by Django 3.2 on 2026-06-03 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0014_auto_20260603_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='ticket_type',
            field=models.CharField(blank=True, default='Issue', max_length=50, null=True),
        ),
    ]
