# Generated by Django 3.2 on 2026-06-16 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0014_auto_20260601_1011'),
        ('hospital', '0016_complaint_department'),
    ]

    operations = [
    ]
