# Generated by Django 3.2 on 2026-06-25 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0017_merge_20260616_1034'),
    ]

    operations = [
        migrations.AddField(
            model_name='dietextramaster',
            name='item_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='dietmaster',
            name='item_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='laundryitemmaster',
            name='item_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
