# Generated by Django 3.2 on 2026-06-30 04:28

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0018_auto_20260625_1209'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrashCartItem',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nursing_station', models.CharField(blank=True, max_length=100, null=True)),
                ('box_category', models.CharField(max_length=100)),
                ('drug_name', models.CharField(max_length=255)),
                ('required_stock', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PhysicalStockEntry',
            fields=[
                ('entry_id', models.AutoField(primary_key=True, serialize=False)),
                ('item_id', models.IntegerField()),
                ('item_name', models.CharField(max_length=255)),
                ('batch_number', models.CharField(max_length=100)),
                ('stock_id', models.IntegerField(blank=True, null=True)),
                ('computer_stock', models.IntegerField(default=0)),
                ('physical_stock', models.IntegerField(default=0)),
                ('stock_date', models.DateField()),
                ('variance', models.IntegerField(default=0)),
                ('is_approved', models.BooleanField(default=False)),
                ('approved_by', models.CharField(blank=True, max_length=100, null=True)),
                ('approved_date', models.DateTimeField(blank=True, null=True)),
                ('approval_notes', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseRequisition',
            fields=[
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('lastmodified_by', models.CharField(blank=True, max_length=100, null=True)),
                ('lastmodified_date', models.DateTimeField(auto_now=True)),
                ('branch_code', models.CharField(blank=True, max_length=100, null=True)),
                ('outlet_code', models.CharField(blank=True, max_length=100, null=True)),
                ('hospital_code', models.CharField(blank=True, max_length=100, null=True)),
                ('pr_number', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('items', djongo.models.fields.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Purchase Order Initiated', 'Purchase Order Initiated'), ('Purchased', 'Purchased'), ('Stock Restocked', 'Stock Restocked')], default='Draft', max_length=30)),
                ('approved_by', models.CharField(blank=True, default='', max_length=100)),
                ('approved_date', models.DateTimeField(blank=True, null=True)),
                ('rejected_by', models.CharField(blank=True, default='', max_length=100)),
                ('rejected_reason', models.TextField(blank=True, default='')),
                ('rejected_date', models.DateTimeField(blank=True, null=True)),
                ('po_initiated_by', models.CharField(blank=True, default='', max_length=100)),
                ('po_initiated_date', models.DateTimeField(blank=True, null=True)),
                ('purchased_by', models.CharField(blank=True, default='', max_length=100)),
                ('purchased_date', models.DateTimeField(blank=True, null=True)),
                ('stock_restocked_by', models.CharField(blank=True, default='', max_length=100)),
                ('stock_restocked_date', models.DateTimeField(blank=True, null=True)),
                ('edited_by', models.CharField(blank=True, default='', max_length=100)),
                ('edited_reason', models.TextField(blank=True, default='')),
                ('edited_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PurchaseReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('lastmodified_by', models.CharField(blank=True, max_length=100, null=True)),
                ('lastmodified_date', models.DateTimeField(auto_now=True)),
                ('branch_code', models.CharField(blank=True, max_length=100, null=True)),
                ('hospital_code', models.CharField(blank=True, max_length=100, null=True)),
                ('purchase_return_bill_no', models.CharField(max_length=30, unique=True)),
                ('purchase_return_bill_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('grn_number', models.CharField(max_length=50)),
                ('vendor_code', models.CharField(blank=True, default='', max_length=50)),
                ('vendor_name', models.CharField(blank=True, default='', max_length=255)),
                ('outlet_code', models.CharField(blank=True, default='', max_length=50)),
                ('items', djongo.models.fields.JSONField(default=list)),
                ('purchase_return_amount', models.CharField(default='0.00', max_length=50)),
                ('gst_amount', models.CharField(default='0.00', max_length=30)),
                ('cgst_amount', models.CharField(default='0.00', max_length=30)),
                ('sgst_amount', models.CharField(default='0.00', max_length=30)),
                ('other_amount', models.CharField(default='0.00', max_length=30)),
                ('round_amount', models.CharField(default='0.00', max_length=30)),
                ('return_remark', models.TextField(blank=True, default='')),
                ('status', models.CharField(default='Returned', max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='admission',
            name='is_admissionActive',
        ),
        migrations.AddField(
            model_name='admission',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='admission',
            name='age_type',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='admission',
            name='cancelled_Reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='admission',
            name='cancelled_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='admission',
            name='edited_Reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='admission',
            name='edited_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='admission',
            name='is_cancelled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='admission',
            name='is_edited',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='admission',
            name='ward_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='dialysisdischargesummary',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='dialysisdischargesummary',
            name='date_of_first_dialysis',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dialysisdischargesummary',
            name='date_of_last_dialysis',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dialysisdischargesummary',
            name='insurance',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='estimatebilling',
            name='firstName',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='estimatebilling',
            name='gender',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='estimatebilling',
            name='lastName',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='estimatebilling',
            name='salutation',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='laundrywardrequest',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='pharmacybilling',
            name='Package_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pharmacybilling',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pharmacybilling',
            name='is_dispatched',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pharmacybilling',
            name='is_received',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pharmacybilling',
            name='patientname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pharmacybilling',
            name='pending_returns',
            field=djongo.models.fields.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='admission',
            name='advance_payments',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='admission',
            name='roomShitingDetails',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='admission',
            name='room_details',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='dialysisdischargesummary',
            name='advice_on_discharge',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='dialysisdischargesummary',
            name='blood_investigations',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='dialysisdischargesummary',
            name='complications_during_hd',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='dialysisdischargesummary',
            name='consultant',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='dialysisdischargesummary',
            name='id_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='dischargebilling',
            name='items',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='estimatebilling',
            name='age',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='estimatebilling',
            name='age_type',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='estimatebilling',
            name='discountPercent',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='estimatebilling',
            name='doctor',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='estimatebilling',
            name='item',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='estimatebilling',
            name='paymentMethod',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='estimatebilling',
            name='roomNo',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='estimatebilling',
            name='uhid',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='laundryitemmaster',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='laundrywardrequest',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='pharmacybilling',
            name='uhid',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='pharmacybilling',
            name='ward_request_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='radiologyreport',
            name='valuedetails',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='referencedoctor',
            name='clinic_address',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='referencedoctor',
            name='resi_address',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='room',
            name='beds',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_kits',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='room',
            name='services',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='summary',
            name='fieldsData',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='velavaninvoice',
            name='items',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.CreateModel(
            name='CrashCartDailyCheck',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('nursing_station', models.CharField(max_length=100)),
                ('expiry_date', models.CharField(blank=True, max_length=50, null=True)),
                ('is_checked', models.BooleanField(default=False)),
                ('checked_by', models.CharField(max_length=100)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.crashcartitem')),
            ],
            options={
                'unique_together': {('date', 'nursing_station', 'item')},
            },
        ),
    ]
