# Generated by Django 3.2 on 2026-06-30 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0019_auto_20260630_0958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientdietorder',
            name='extra_items',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
