# Generated by Django 3.2 on 2026-07-01 05:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0020_alter_patientdietorder_extra_items'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImplantRequest',
            fields=[
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('lastmodified_by', models.CharField(blank=True, max_length=100, null=True)),
                ('lastmodified_date', models.DateTimeField(auto_now=True)),
                ('branch_code', models.CharField(blank=True, max_length=100, null=True)),
                ('outlet_code', models.CharField(blank=True, max_length=100, null=True)),
                ('hospital_code', models.CharField(blank=True, max_length=100, null=True)),
                ('ImplantRequest_id', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('uhid', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('inpatient_number', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('surgeon_id', models.CharField(blank=True, max_length=100, null=True)),
                ('surgery_ref', models.CharField(blank=True, max_length=100, null=True)),
                ('items', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(default='Pending', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'hospital_implant_request',
                'ordering': ['-created_date'],
            },
        ),
        migrations.CreateModel(
            name='IpAdvance_Refund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refund_bill_no', models.CharField(max_length=30, unique=True)),
                ('refund_date', models.DateTimeField()),
                ('refund_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('bill_no', models.CharField(max_length=30)),
                ('ip_number', models.CharField(max_length=50)),
                ('uhid', models.CharField(max_length=50)),
                ('advance_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('remarks', models.TextField(blank=True, default='')),
                ('bill_type', models.CharField(max_length=20)),
                ('billTypeNo', models.CharField(blank=True, default='', max_length=20)),
                ('status', models.CharField(default='Pending', max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='AdmissionRefund',
        ),
        migrations.RemoveField(
            model_name='billing',
            name='billtype',
        ),
        migrations.AddField(
            model_name='billing',
            name='bill_type',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='modules',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='velavanitems',
            name='category',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='cashcountershiftdetails',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
