# Generated by Django 3.2 on 2026-07-15 11:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0022_auto_20260715_1212'),
    ]

    operations = [
        migrations.CreateModel(
            name='Internship',
            fields=[
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('lastmodified_by', models.CharField(blank=True, max_length=100, null=True)),
                ('lastmodified_date', models.DateTimeField(auto_now=True)),
                ('branch_code', models.CharField(blank=True, max_length=100, null=True)),
                ('outlet_code', models.CharField(blank=True, max_length=100, null=True)),
                ('hospital_code', models.CharField(blank=True, max_length=100, null=True)),
                ('intern_id', models.IntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('student_name', models.CharField(max_length=255)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('mobile_number', models.CharField(blank=True, max_length=20, null=True)),
                ('college', models.CharField(max_length=255)),
                ('department', models.CharField(max_length=255)),
                ('degree', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('duration', models.CharField(max_length=100)),
                ('is_hosteller', models.BooleanField(default=False)),
                ('fee_per_month', models.DecimalField(decimal_places=2, default=3500.0, max_digits=10)),
                ('hostel_fee_per_month', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('payment_status', models.CharField(default='Pending', max_length=50)),
                ('payment_details', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
