# Generated by Django 3.2 on 2026-07-16 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0023_internship'),
    ]

    operations = [
        migrations.CreateModel(
            name='InternshipCertificateTemplate',
            fields=[
                ('template_id', models.IntegerField(default=1, primary_key=True, serialize=False)),
                ('description', models.TextField(default='This is to certify that [Student Name] has successfully completed their internship in the department of [Department] from [Start Date] to [End Date]. During this period, their performance was [Performance].')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
