# Generated by Django 3.2 on 2026-07-16 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0024_internshipcertificatetemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='internship',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='internship',
            name='approved_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='internship',
            name='cert_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='internship',
            name='cert_template_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='internship',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='internship',
            name='deleted_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='internship',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='internship',
            name='discount_remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
