# Generated by Django 3.2 on 2026-07-16 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0025_auto_20260716_0954'),
    ]

    operations = [
        migrations.AddField(
            model_name='internshipcertificatetemplate',
            name='title',
            field=models.CharField(default='Certificate Template', max_length=255),
        ),
        migrations.AlterField(
            model_name='internshipcertificatetemplate',
            name='template_id',
            field=models.IntegerField(editable=False, primary_key=True, serialize=False),
        ),
    ]
