# Generated by Django 3.2 on 2026-07-16 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0026_auto_20260716_1117'),
    ]

    operations = [
        migrations.AddField(
            model_name='communicationlog',
            name='template_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
