# Generated by Django 3.2 on 2026-07-16 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0027_add_template_name_to_communicationlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internship',
            name='intern_id',
            field=models.CharField(editable=False, max_length=50, primary_key=True, serialize=False),
        ),
    ]
