# Generated by Django 3.2 on 2026-07-21 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0022_user_session'),
        ('hospital', '0028_alter_internship_intern_id'),
    ]

    operations = [
    ]
