# Generated by Django 3.2 on 2026-07-21 11:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0030_auto_20260721_1637'),
    ]

    operations = [
        migrations.CreateModel(
            name='ABHAProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('lastmodified_by', models.CharField(blank=True, max_length=100, null=True)),
                ('lastmodified_date', models.DateTimeField(auto_now=True)),
                ('branch_code', models.CharField(blank=True, max_length=100, null=True)),
                ('outlet_code', models.CharField(blank=True, max_length=100, null=True)),
                ('hospital_code', models.CharField(blank=True, max_length=100, null=True)),
                ('abha_number', models.CharField(max_length=50, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('dob', models.CharField(blank=True, max_length=50, null=True)),
                ('gender', models.CharField(blank=True, max_length=10, null=True)),
                ('abha_address', models.CharField(blank=True, max_length=100, null=True)),
                ('abha_mobile', models.CharField(blank=True, max_length=20, null=True)),
                ('abha_photo', models.TextField(blank=True, null=True)),
                ('abha_status', models.CharField(blank=True, max_length=50, null=True)),
                ('abha_type', models.CharField(blank=True, max_length=50, null=True)),
                ('abha_district_name', models.CharField(blank=True, max_length=100, null=True)),
                ('abha_state_name', models.CharField(blank=True, max_length=100, null=True)),
                ('abha_pincode', models.CharField(blank=True, max_length=20, null=True)),
                ('abha_full_address', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='patient',
            name='aadhaar_number',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='abha_address',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='abha_district_name',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='abha_full_address',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='abha_mobile',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='abha_photo',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='abha_pincode',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='abha_state_name',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='abha_status',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='abha_type',
        ),
    ]
