# Generated by Django 3.2 on 2026-07-29 06:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0031_auto_20260721_1643'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorFeeCuts',
            fields=[
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('lastmodified_by', models.CharField(blank=True, max_length=100, null=True)),
                ('lastmodified_date', models.DateTimeField(auto_now=True)),
                ('branch_code', models.CharField(blank=True, max_length=100, null=True)),
                ('outlet_code', models.CharField(blank=True, max_length=100, null=True)),
                ('hospital_code', models.CharField(blank=True, max_length=100, null=True)),
                ('ip_number', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('uhid', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(default='Pending', max_length=50)),
                ('approved_by', models.CharField(blank=True, max_length=255, null=True)),
                ('approved_date', models.DateTimeField(blank=True, null=True)),
                ('doctor_breakdown', models.JSONField(blank=True, default=list, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='licence_master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('lastmodified_by', models.CharField(blank=True, max_length=100, null=True)),
                ('lastmodified_date', models.DateTimeField(auto_now=True)),
                ('branch_code', models.CharField(blank=True, max_length=100, null=True)),
                ('outlet_code', models.CharField(blank=True, max_length=100, null=True)),
                ('hospital_code', models.CharField(blank=True, max_length=100, null=True)),
                ('s_no', models.PositiveIntegerField(blank=True, null=True, unique=True)),
                ('licence_name', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='licencemasterdetails',
            fields=[
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('lastmodified_by', models.CharField(blank=True, max_length=100, null=True)),
                ('lastmodified_date', models.DateTimeField(auto_now=True)),
                ('branch_code', models.CharField(blank=True, max_length=100, null=True)),
                ('outlet_code', models.CharField(blank=True, max_length=100, null=True)),
                ('hospital_code', models.CharField(blank=True, max_length=100, null=True)),
                ('s_no', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('licence_name', models.CharField(max_length=255)),
                ('license_number', models.CharField(blank=True, max_length=255, null=True)),
                ('valid_from', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('Intimation_90days_about_expiry', models.CharField(blank=True, default='90 Day(s) Before the Due Date', max_length=100, null=True)),
                ('Intimation_60days_about_expiry', models.CharField(blank=True, default='60 Day(s) Before the Due Date', max_length=100, null=True)),
                ('Intimation_30days_about_expiry', models.CharField(blank=True, default='30 Day(s) Before the Due Date', max_length=100, null=True)),
                ('Intimation_7days_about_expiry', models.CharField(blank=True, default='7 Day(s) Before the Due Date', max_length=100, null=True)),
                ('Intimation_1day_about_expiry', models.CharField(blank=True, default='1 Day(s) Before the Due Date', max_length=100, null=True)),
                ('incharge', models.CharField(blank=True, max_length=255, null=True)),
                ('respective_person', models.CharField(blank=True, max_length=255, null=True)),
                ('is_90days', models.BooleanField(default=False)),
                ('is_60days', models.BooleanField(default=False)),
                ('is_30days', models.BooleanField(default=False)),
                ('is_7days', models.BooleanField(default=False)),
                ('is_1day', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UHIDCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefix', models.CharField(max_length=20, unique=True)),
                ('last_sequence', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='purchasereturn',
            name='cgst_amount',
        ),
        migrations.RemoveField(
            model_name='purchasereturn',
            name='gst_amount',
        ),
        migrations.RemoveField(
            model_name='purchasereturn',
            name='id',
        ),
        migrations.RemoveField(
            model_name='purchasereturn',
            name='other_amount',
        ),
        migrations.RemoveField(
            model_name='purchasereturn',
            name='round_amount',
        ),
        migrations.RemoveField(
            model_name='purchasereturn',
            name='sgst_amount',
        ),
        migrations.RemoveField(
            model_name='purchasereturn',
            name='vendor_code',
        ),
        migrations.RemoveField(
            model_name='purchasereturn',
            name='vendor_name',
        ),
        migrations.AddField(
            model_name='communicationlog',
            name='sender',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='purchaserequisition',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Returned', 'Returned')], default='Draft', max_length=30),
        ),
        migrations.AlterField(
            model_name='purchasereturn',
            name='grn_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='purchasereturn',
            name='purchase_return_bill_no',
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='purchasereturn',
            name='return_remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='purchasereturn',
            name='status',
            field=models.CharField(default='Pending', max_length=50),
        ),
    ]
